[package]

name = "piston2d-opengl_graphics"
version = "0.32.0"
authors = [
    "bvssvni <bvssvni@gmail.com>",
    "Coeuvre <coeuvre@gmail.com>",
    "gmorenz",
    "leonkunert <info@leonkunert.de>",
    "mitchmindtree <me@michellnordine.com>",
    "Christiandh",
    "Apointos",
    "ccgn",
    "reem",
    "TyOverby <ty@pre-alpha.com>"
]
keywords = ["opengl", "graphics", "2d", "piston"]
description = "An OpenGL 2D back-end for the Piston game engine"
license = "MIT"
readme = "README.md"
repository = "https://github.com/PistonDevelopers/opengl_graphics.git"
homepage = "https://github.com/PistonDevelopers/opengl_graphics"

[lib]
name = "opengl_graphics"
path = "src/lib.rs"

[dependencies.image]
version = "0.10.0"

[dependencies]
rusttype = "0.2.1"
gl = "0.6.0"
piston-shaders_graphics2d = "0.1.0"
piston-texture = "0.5.0"
piston2d-graphics = "0.17.0"
shader_version = "0.2.0"
fnv = "1.0.2"

[dev-dependencies]
piston = "0.25.0"
pistoncore-sdl2_window = "0.34.0"

[build-dependencies]
khronos_api = "0.0.8"
